name: build-ci.yml
on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  call-common-workflow:
    uses: "./.github/workflows/build-common.yml"

  additional-steps:
    needs: call-common-workflow
    runs-on: ubuntu-latest

    steps:
      - name: "Another one"
        run: "echo 123"
