name: build-ci.yml
on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  common:
    uses: "./.github/workflows/build-common.yml"

  docker-image-build:
    needs: common
    runs-on: ubuntu-latest

    steps:
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Files
        run: |
          pwd
          ls -al ${{ github.workspace }}

      - name: Build and push WebApp image
        working-directory: "./src/WCCG.PAS.Referrals.API"
        run: |
          docker build -t pas/referrals.api:latest .
