name: build-ci.yml
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  call-common-workflow:
    uses: "./.github/workflows/build-common.yml"

  additional-steps:
    needs: call-common-workflow
    runs-on: ubuntu-latest
