name: build-ci.yml
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  call-common-workflow:
    uses: "./.github/workflows/build-common.yml"

  additional-steps:
    needs: call-common-workflow
    runs-on: ubuntu-latest

    steps:
      - name: Build Docker Image
        working-directory: .
        run: |
          docker build -t /dockerTest:${{ github.sha }} .
